
language: python

python:
  - { PATH: "{{Python37}}",
      VERSION: 3.7,
      DIST: std,
      PYINT: python3.7,
      LD_LIBRARY_PATH: /usr/local/Python-3.7.2 }
  
virtualenv:
  - path: {{ospathjoin(root_path, pickname("$NAME_JENKINS", project_name + "_$VERSION_$DIST_$NAME"), "_venv")}}
  
before_script:
  - $PYINT -m pip install --no-cache-dir --no-deps --index http://localhost:8067/simple/ pyquickhelper jyquickhelper mlinsights pymlbenchmark wrapclib --upgrade --extra-index-url=https://pypi.python.org/simple/
  - $PYINT -m pip install --no-cache-dir --no-deps --index http://localhost:8067/simple/ skl2onnx onnxmltools onnx onnxruntime onnxconverter_common --upgrade --extra-index-url=https://pypi.python.org/simple/
  - $PYINT -m pip install --no-cache-dir --no-deps --index http://localhost:8067/simple/ mlprodict mlinsights pandas_streaming --upgrade --extra-index-url=https://pypi.python.org/simple/
  - $PYINT -m pip install --no-cache-dir --no-deps --index http://localhost:8067/simple/ asv scikit-learn --upgrade --extra-index-url=https://pypi.python.org/simple/
  - $PYINT -m pip install xgboost lightgbm py-spy
  - $PYINT -m pip freeze

script:
  # scikit-learn
  - { CMD: "$PYINT -u scikit-learn/bench_plot_gridsearch_cache.py", NAME: "SKL_CACHE", TIMEOUT: 4800 }
  # onnxruntime
  - { CMD: "$PYINT -u onnx/bench_plot_onnxruntime_logreg.py", NAME: "ORT_LR" }
  - { CMD: "$PYINT -u onnx/bench_plot_onnxruntime_mlp.py", NAME: "ORT_MLP", TIMEOUT: 2400 }
  - { CMD: "$PYINT -u onnx/bench_plot_onnxruntime_decision_tree.py", NAME: "ORT_DT" }
  - { CMD: "$PYINT -u onnx/bench_plot_onnxruntime_decision_tree_reg.py", NAME: "ORT_DT_REG" }
  - { CMD: "$PYINT -u onnx/bench_plot_onnxruntime_random_forest.py", NAME: "ORT_RF", TIMEOUT: 3600 }
  - { CMD: "$PYINT -u onnx/bench_plot_onnxruntime_knn.py", NAME: "ORT_KNN" }
  - { CMD: "$PYINT -u onnx/bench_plot_skl2onnx_unittest.py", NAME: "ORT_UNIT" }
  - { CMD: "$PYINT -u onnx/bench_plot_onnxruntime_casc_add.py", NAME: "ORT_CASCADD", TIMEOUT: 1800 }
  - { CMD: "$PYINT -u onnx/bench_plot_onnxruntime_casc_scaler.py", NAME: "ORT_CASCSCL", TIMEOUT: 2400 }
  - { CMD: "$PYINT -u onnx/bench_plot_onnxruntime_casc_mlp.py", NAME: "ORT_CASCMLP" }
  - { CMD: "$PYINT -u onnx/bench_plot_datasets_num.py", NAME: "ORT_DSNUM" }
  # module
  - { CMD: "$PYINT -u modules/bench_plot_re2.py", NAME: "MOD_RE2" }
  # documentation
  - { CMD: "$PYINT -c \"from sphinx.cmd.build import build_main;build_main(['-j2','-v','-T','-b','html','-d','dist/doctrees','_doc','dist/html'])\"", NAME: "UT" }
  - { CMD: "$PYINT -m pytest", NAME: "TEST" }
  # benchmark
  - { CMD: "bash sklbench/run_sklbenchmark.sh", NAME: "SKLBENCH", TIMEOUT: 12000, SCHEDULER: "H H(3-4) * * 1", CLEAN: "0" }
  - { CMD: "bash sklbench/run_bench_skl2onnx_cpp.sh", NAME: "SKLBENCHONNX_CPP", SCHEDULER: "H H(7-8) * * 1", CLEAN: "0" }
  - { CMD: "bash sklbench/run_bench_onnxruntime.sh", NAME: "SKLORT", SCHEDULER: "H H(11-12) * * 1", CLEAN: "0" }
  - { CMD: "bash sklbench/run_bench_skl2onnx.sh", NAME: "SKLBENCHONNX", SCHEDULER: "H H(7-8) * * 6", CLEAN: "0" }
  # profile
  - { CMD: "bash sklbench/run_profile_skl2onnx_classifier.sh", NAME: "SKLPROFILEONNX", SCHEDULER: "H H(6-7) * * 6", TIMEOUT: 7200 }
  - { CMD: "bash sklbench/run_profile_skl2onnx_regressor.sh", NAME: "SKLPROFILEONNXREG", SCHEDULER: "H H(6-7) * * 5", TIMEOUT: 7200 }

after_script:
  - if [ ${NAME} == "UT" ] then ls dist/html/*.html fi
